PREFIX ec: <http://www.ebu.ch/metadata/ontologies/ebucoreplus#>
SELECT ?entity ?publication ?channelName ?start (GROUP_CONCAT(DISTINCT STR(?country); SEPARATOR="|") AS ?productionCountries)
WHERE {
  ?entity ec:hasIdentifier ?id .
  ?id ec:name "PRID" ; ec:identifierValue "POW_05977062" .
  ?entity ec:hasPublication ?publication .
  ?publication ec:hasPublicationChannel ?channel .
  ?channel ec:name ?channelName .
  ?publication ec:hasStartDateTime ?start .
  OPTIONAL {
    ?publication ec:hasProductionCountry ?pc .
    OPTIONAL { ?pc ec:altLabel ?country . }
  }
}
GROUP BY ?entity ?publication ?channelName ?start
LIMIT 20

