PREFIX ec: <http://www.ebu.ch/metadata/ontologies/ebucoreplus#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT
    ?entity ?id
WHERE {
    # Base row shape: one row per publication
    ?entity ec:hasIdentifier ?id .
      ?id ec:name "PRID" .
      ?id ec:identifierValue "POMS_AT_10136575" .


}
