PREFIX ec: <http://www.ebu.ch/metadata/ontologies/ebucoreplus#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT *
WHERE {
    ?entity ec:hasIdentifier ?id .
      ?id ec:name "PRID" .
      ?id ec:identifierValue "%s" .
    ?entity ec:hasPublication ?publication .
      ?publication ec:hasPublicationChannel ?channel .
         ?channel ec:name ?channelName .
      ?publication ec:hasStartDateTime ?start .
    ?entity ec:hasPublisher/ec:hasAgent/ec:name ?broadcasterName .
    OPTIONAL { ?publication ec:hasEndDateTime ?end . }
    OPTIONAL { ?entity ec:title ?title . }
    OPTIONAL { ?entity ec:contentDescription ?description . }
    OPTIONAL { ?entity ec:hasDateCreated ?dateCreated . }
    OPTIONAL {
        ?entity ec:hasGenre ?genreNode .
        BIND(str(?genreNode) AS ?genreId)
        OPTIONAL { ?genreNode skos:prefLabel ?genreLabel . }
    }
    OPTIONAL {
        ?entity ec:hasRating ?rating .
        ?rating a ?ratingClass .
        OPTIONAL { ?rating ec:ratingValue ?ratingValue . }
        BIND(str(?ratingClass) AS ?ratingType)
    }
}




