PREFIX ec: <http://www.ebu.ch/metadata/ontologies/ebucoreplus#>
SELECT ?prid
WHERE {
    ?entity ec:hasIdentifier ?id .
       ?id ec:name "PRID" .
      ?id ec:identifierValue ?prid .
    ?entity ec:isPartOf ?part .
      ?part ec:hasIdentifier ?partId .
      ?partId ec:name "PRID" .
      ?partId ec:identifierValue "%s" .

    OPTIONAL { ?entity ec:title ?title . }
    OPTIONAL { ?entity ec:contentDescription ?description . }
    OPTIONAL { ?entity ec:hasDateCreated ?dateCreated . }
}




