PREFIX ec: <http://www.ebu.ch/metadata/ontologies/ebucoreplus#>
SELECT
    ?entity
    ?prid
    (SAMPLE(?title) as ?title)
    (SAMPLE(?description) as ?description)
    (SAMPLE(?dateCreated) as ?dateCreated)
    (GROUP_CONCAT(DISTINCT ?broadcaster; SEPARATOR="|") AS ?broadcasters)

WHERE {
    ?entity ec:hasIdentifier ?id .
       ?id ec:name "PRID" .
      ?id ec:identifierValue ?prid .
    ?entity ec:isPartOf ?part .
      ?part ec:hasIdentifier ?partId .
      ?partId ec:name "PRID" .
      ?partId ec:identifierValue "%s" .

    OPTIONAL { ?entity ec:title ?title . }
    OPTIONAL { ?entity ec:contentDescription ?description . }
    OPTIONAL { ?entity ec:hasDateCreated ?dateCreated . }
    OPTIONAL {
        ?entity ec:hasPublisher/ec:hasAgent/ec:hasIdentifier/ec:identifierValue ?broadcaster .
    }
}
group by ?entity ?prid




